spring:
  application:
    name: testDB
  datasource:
    url: jdbc:mysql://43.255.28.191:3306/testdemo?serverTimezone=UTC&useUnicode=true&zeroDateTimeBehavior=convertToNull&autoReconnect=true&characterEncoding=utf-8
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

server:
  port: 9004